name: trilium-next
services:
  app:
    image: triliumnext/notes:v0.91.6
    restart: unless-stopped
    environment:
      TRILIUM_DATA_DIR: /home/node/trilium-data
    x-casaos:
      envs:
        - container: TRILIUM_DATA_DIR
          description:
            en_us: ''
    ports:
      - target: 8080
        published: 8782
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /home/node/trilium-data
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone:ro
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: TriliumNext Notes is a hierarchical note taking application with focus on building large personal knowledge bases
  tagline:
    en_us: TriliumNext Notes Is A Hierarchical Note Taking Application With Focus On Building Large Personal Knowledge Bases
  developer: ''
  author: "Kushal Azim Ekram"
  icon: https://raw.githubusercontent.com/TriliumNext/Notes/refs/heads/develop/images/icon-color.svg
  thumbnail: https://raw.githubusercontent.com/TriliumNext/Notes/refs/heads/develop/images/icon-color.svg
  title:
    en_us: TriliumNext
  category: KuStoreApps
  port_map: '8782'
